export const TestColls = {
    collections:
        [
            {
                collection_name: 'pigs',
                collection_id: '873649273hd982374hd0',
                creator: "narni",
                floor_price: '34',
                volume: '44',
                logo: "",
                banner: '',
                category: 'animal',
                created_at: '',
                royalty: 8,
            },
            {
                collection_name: 'cats',
                collection_id: '873634273hd982374hf0',
                creator: "erfan",
                floor_price: '4',
                volume: '14',
                logo: "",
                banner: '',
                category: 'animal',
                created_at: '',
                royalty: 15,
            },
            {
                collection_name: 'airplanes',
                collection_id: '873649273d482374h890',
                creator: "narni",
                floor_price: '50',
                volume: '45',
                logo: "",
                banner: '',
                category: 'utilities',
                created_at: '',
                royalty: 10,
            },
            {
                collection_name: 'flowers',
                collection_id: '85555246hd98245930h',
                creator: "mehdi",
                floor_price: '12',
                volume: '6',
                logo: "",
                banner: '',
                category: 'nature',
                created_at: '',
                royalty: 5,
            },
            {
                collection_name: 'designs',
                collection_id: '855555d2gc66d23c0h',
                creator: "mahsa",
                floor_price: '5',
                volume: '7',
                logo: "",
                banner: '',
                category: 'art',
                created_at: '',
                royalty: 7,
            },
            {
                collection_name: 'airplanes',
                collection_id: '873649273d482374h890',
                creator: "narni",
                floor_price: '50',
                volume: '45',
                logo: "",
                banner: '',
                category: 'utilities',
                created_at: '',
                royalty: 9,
            },
            {
                collection_name: 'flowers',
                collection_id: '85555246hd98245930h',
                creator: "mehdi",
                floor_price: '12',
                volume: '6',
                logo: "",
                banner: '',
                category: 'nature',
                created_at: '',
                royalty: 2,
            },
            {
                collection_name: 'designs',
                collection_id: '855555d2gc66d23c0h',
                creator: "mahsa",
                floor_price: '5',
                volume: '7',
                logo: "",
                banner: '',
                category: 'art',
                created_at: '',
                royalty: 6,
            },
            {
                collection_name: 'cats',
                collection_id: '873634273hd982374hf0',
                creator: "erfan",
                floor_price: '4',
                volume: '14',
                logo: "",
                banner: '',
                category: 'animal',
                created_at: '',
                royalty: 4,
            },
            {
                collection_name: 'airplanes',
                collection_id: '873649273d482374h890',
                creator: "narni",
                floor_price: '50',
                volume: '45',
                logo: "",
                banner: '',
                category: 'utilities',
                created_at: '',
                royalty: 5,
            },

        ]
}